# https://pnpm.io/ja/pnpm-workspace_yaml
packages:
  - "packages/*"
catalog:
  valibot: ^1.2.0
catalogs:
  ts:
    "@types/node": 22.19.7
    typescript: 5.9.3
  prisma:
    "@prisma/adapter-pg": ^7.3.0
    "@prisma/client": ^7.3.0
    "pg": ^8.18.0
    "prisma": ^7.3.0

# https://pnpm.io/ja/workspaces#syncinjecteddepsafterscripts
syncInjectedDepsAfterScripts:
  - build

# https://pnpm.io/ja/settings#minimumreleaseage
minimumReleaseAge: 4320 # 3日間 (4,320分)

# https://pnpm.io/ja/settings#ignoredbuiltdependencies
ignoredBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - lefthook
  - prisma
  - sharp
