# https://pnpm.io/ja/pnpm-workspace_yaml
packages:
  - "packages/*"
catalog:
  "@logtape/logtape": ^2.0.2
  next: ^16.2.6
  valibot: ^1.2.0
catalogs:
  ts:
    "@types/node": 22.19.7
    tsx: 4.21.0
    typescript: 5.9.3
  prisma:
    "@prisma/adapter-pg": ^7.8.0
    "@prisma/client": ^7.8.0
    pg: ^8.21.0
    prisma: ^7.8.0
  react:
    "@types/react": ^19
    "@types/react-dom": ^19
    react: ^19.2.6
    react-dom: ^19.2.6
  vitest:
    "@vitest/coverage-v8": "^4.1.7"
    "vitest": "^4.1.7"

# https://pnpm.io/ja/workspaces#syncinjecteddepsafterscripts
syncInjectedDepsAfterScripts:
  - build

# https://pnpm.io/ja/settings#minimumreleaseage
minimumReleaseAge: 4320 # 3日間 (4,320分)

# https://pnpm.io/ja/settings#ignoredbuiltdependencies
ignoredBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - lefthook
  - prisma
  - sharp
